# 服务器配置
server:
  host: "127.0.0.1"
  port: 5000
  debug: true

# 默认串口配置
default_serial_config:
  port_name: 'COM10'
  baudrate: 9600
  timeout: 1

# Modbus配置
modbus:
  response_timeout: 1 # 响应超时时间（秒）
  retries: 3 # 重试次数

# TCP服务器配置
tcp_server:
  host: 127.0.0.1     # 服务器地址，使用127.0.0.1表示仅本机访问，0.0.0.0表示允许所有地址访问
  # host: 0.0.0.0     # 服务器地址，使用127.0.0.1表示仅本机访问，0.0.0.0表示允许所有地址访问
  port: 8880          # 服务器端口
  max_connections: 5  # 最大连接数
  buffer_size: 4096   # 缓冲区大小
  max_bytes_per_request: 128  # 每次接收和发送的最大字节数量

max_entries: 1024 # 收发数据队列最大长度
max_workers: 10 # 最大处理请求数量
