# 服务器配置
server:
  host: "127.0.0.1"
  port: 5000
  debug: true

# 默认串口配置
default_serial_config:
  port_name: 'COM10'
  baudrate: 9600
  timeout: 1

# Modbus配置
modbus:
  response_timeout: 1 # 响应超时时间（秒）
  retries: 3 # 重试次数

max_entries: 100 # 数据保留策略
max_workers: 10 # 最大处理请求数量
