modbus:
  retries: 3
serial:
  receive_error_time: 2.0
  receive_time: 0.05
  send_error_time: 2.0
  send_time: 0.05
serial_ports:
  - baudrate: 9600
    description: Ch B
    name: COM5
  - baudrate: 9600
    description: Ch D
    name: COM7
  - baudrate: 9600
    description: Ch H
    name: COM11
tcp_server:
  buffer_size: 4096
  host: 192.168.196.206
  max_bytes_per_request: 1024
  max_connections: 5
  port: 8889
