modbus:
  retries: 3
serial:
  receive_error_time: 2.0
  receive_time: 0.05
  send_error_time: 2.0
  send_time: 0.05
serial_ports:
- baudrate: 9600
  description: 通风柜
  name: COM5
- baudrate: 9600
  description: 温度传感器
  name: COM7
- baudrate: 9600
  description: 湿度传感器
  name: COM11
tcp_server:
  buffer_size: 4096
  host: 127.0.0.1
  max_bytes_per_request: 128
  max_connections: 5
  port: 7779
